### ISSUE TITLE
Missing Homo_sapiens_assembly38.fasta when running run_tests.sh

### ISSUE THREAD

**Issue by tbooth** [adamewing/methylartist-tests#1]
The script makes reference to the file: `/home/data/ref/hg38/Homo_sapiens_assembly38.fasta`

It seems what is needed is this standard file from GATK:

https://media.githubusercontent.com/media/broadinstitute/gatk/master/src/test/resources/large/Homo_sapiens_assembly38.fasta.gz

This version is block-gzip compressed so it's not necessary to `gunzip` it before use, just to download it. Maybe something could be added to the script like:

```
if not [ -e data/Homo_sapiens_assembly38.fasta.gz ] ; then
    echo "Please download the GATK HG38 reference. For example:"
    echo "wget -P data https://media.githubusercontent.com/media/broadinstitute/gatk/master/src/test/resources/large/Homo_sapiens_assembly38.fasta.gz"
fi
```

and then change the path in the three commands which use this file.

**Comment by adamewing** [comment]
Thanks! Done in b90587d
