### ISSUE TITLE
Megalodon.db

### ISSUE THREAD

**Issue by Manorma1234-tech** [adamewing/methylartist-tests#2]
I ran the tests they were all successful, Now I'm trying how to get this .sample.megalodon.db file, I have my output in the bam file only.  

**data/MCF7_ATCC.sample.haplotag.bam data/MCF7_ATCC.sample.megalodon.db
data/MCF7_ECACC.sample.haplotag.bam data/MCF7_ECACC.sample.megalodon.db**

**Comment by adamewing** [comment]
Hey there, not quite clear on what you mean but I think you might be asking how to run this on your own data where you just have .bam files and not .db files, is that correct?

If so, and if the .bam files have the MM/ML tags for modified bases, you can feed them to methylartist via the -b/--bam option.

**Comment by Manorma1234-tech** [comment]
Hello, Yes I have .bam files, I sort my bam file index it, and merge it into a single .bam file. But When I run with the segmeth command there is an error showing --ref --motifs required for -bams? Is it asking for my references Genome, and what about motifs?

**Comment by adamewing** [comment]
Ok, good, yes `--ref` should point to a reference genome that has been indexed via `samtools faidx`, and `--motifs` is `CG` if you're looking at CpG methylation `A` if you're looking at m6a, etc.

**Comment by Manorma1234-tech** [comment]
okay Thank you. I have another query, the .bam file has NC00001.11 header but the requirement is in chr1, chr2, format. Can you please tell me how to do that? I am trying samtool reheader function but it is giving me same output in this "NC00001.11" not in chr1.

**Comment by adamewing** [comment]
There isn't a requirement for a particular naming scheme (unless I've missed something?) so you should be able to use coordinates like `NC00001.11:12345-22345`, let me know if that makes sense as I'm not sure I understand.

**Comment by Manorma1234-tech** [comment]
Command given:
methylartist scoredist -n 300000 -b output.sorted.bam --ref /home/singhrajender/Documents/manorma/nanopore_data/NanoRef/hg38.fa.fai --motif CG -m m

Error:
2024-05-21 17:08:58,030 starting methylartist with command: /home/singhrajender/.local/bin/methylartist scoredist -n 300000 -b output.sorted.bam --ref /home/singhrajender/Documents/manorma/nanopore_data/NanoRef/hg38.fa.fai --motif CG -m m
[E::fai_build_core] Format error, unexpected "c" at line 1
Traceback (most recent call last):
  File "/home/singhrajender/.local/bin/methylartist", line 5592, in <module>
    main()
  File "/home/singhrajender/.local/bin/methylartist", line 5272, in main
    args.func(args)
  File "/home/singhrajender/.local/bin/methylartist", line 1786, in scoredist
    sample[os.path.basename(bam)] = sample_bam(bam, args.motif, args.ref, int(args.n))
  File "/home/singhrajender/.local/bin/methylartist", line 761, in sample_bam
    ref = pysam.Fastafile(ref)
  File "pysam/libcfaidx.pyx", line 123, in pysam.libcfaidx.FastaFile.__cinit__
  File "pysam/libcfaidx.pyx", line 183, in pysam.libcfaidx.FastaFile._open
OSError: error when opening file `/home/singhrajender/Documents/manorma/nanopore_data/NanoRef/hg38.fa.fai`

We are facing the above error with reference file. We have done reference genome indexing using "samtools faidx" tool.
Below are the attached reference index file data:
chr1	248956422	6	50	51
chr10	133797422	253935564	50	51
chr11	135086622	390408942	50	51
chr11_KI270721v1_random	100316	528197322	50	51
chr12	133275309	528299652	50	51
chr13	114364328	664240475	50	51
chr14	107043718	780892097	50	51
chr14_GL000009v2_random	201709	890076715	50	51

Below is the .bam file data:
NC_000001.11	10000	10423	b112a3cb-817b-4c50-abb8-84de3900b738	0	+
NC_000001.11	10000	10468	3ef37e5d-5b44-4249-b161-93e102200aad	0	+
NC_000001.11	10000	10468	ae3cb4a1-d80d-4103-8588-0c8c7a042735	0	+
NC_000001.11	10000	23012	e4ae9864-f99a-4fcd-b391-fc61bab567e8	0	+
NC_000001.11	10000	10467	36d1e1b8-1167-4775-9d70-7068dd0b2fa8	0	+
NC_000001.11	10000	10468	36d1e1b8-1167-4775-9d70-7068dd0b2fa8	0	+
NC_000001.11	10000	10368	12807309-45c8-4668-9ff1-b60724a61f28	0	+
NC_000001.11	10000	10468	b5d4ccfa-30a5-4fc2-b5dd-45ebfcf030f7	0	+
NC_000001.11	10000	10374	986037a0-a0fe-45ea-9181-d69d3db5034b	0	+
NC_000001.11	10000	10468	686213fa-7bcb-48ab-b84c-44bfceb59e57	0	+

<< ValueError: invalid contig `chr1` >> 

How to solve the above error?

**Comment by adamewing** [comment]
ah the reference .fasta file should be the same one as was used to create the .bam files

**Comment by Manorma1234-tech** [comment]
Is there any way to solve this issue? I tried reheader command from samtools but it didn't work? Can you suggest something?

**Comment by adamewing** [comment]
One issue I didn't pick up on before is that `--ref` should point to the .fa file not the .fa.fai file.

The easiest way to address this is to point `--ref` to the same reference genome as was used to create the .bam you are using.

**Comment by Manorma1234-tech** [comment]
hi again,

I have a problem regading graph generated by segplot. every time I tried the graph is blank and there are so many o(zero) in .csv file and nan in .tsv file after trying next command I get a error :
Traceback (most recent call last):
  File "/home/.local/bin/methylartist", line 5592, in <module>
    main()
  File "/home/.local/bin/methylartist", line 5272, in main
    args.func(args)
  File "/home/.local/bin/methylartist", line 2711, in segplot
    sns_plot = sns.FacetGrid(plot_data, row='samplegroup', hue='sample', aspect=15, height=.5, palette=args.palette)
  File "/home/.local/lib/python3.10/site-packages/seaborn/axisgrid.py", line 462, in __init__
    axes = fig.subplots(nrow, ncol, **kwargs)
  File "/home/.local/lib/python3.10/site-packages/matplotlib/figure.py", line 930, in subplots
    gs = self.add_gridspec(nrows, ncols, figure=self, **gridspec_kw)
  File "/home/.local/lib/python3.10/site-packages/matplotlib/figure.py", line 1542, in add_gridspec
    gs = GridSpec(nrows=nrows, ncols=ncols, figure=self, **kwargs)
  File "/home/.local/lib/python3.10/site-packages/matplotlib/gridspec.py", line 378, in __init__
    super().__init__(nrows, ncols,
  File "/home/.local/lib/python3.10/site-packages/matplotlib/gridspec.py", line 48, in __init__
    raise ValueError(
ValueError: Number of rows must be a positive integer, not 0

Please suggest what should I do?
